In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load dataset
df = pd.read_csv("Uncleaned hotel_bookings.csv")

# Preview data
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [15]:
# Basic Info Check
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119390 non-null  int64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(3), int64(17), str(12)
memory usage: 29.1 MB

In [6]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [31]:
# Check missing values:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
total_guests                      0
dtype: int64

In [21]:
#Fixing datatypes:
#1. Children column stored as float convert it to int

df['children'] = df['children'].fillna(0).astype(int)

In [23]:
# replacing null with unknown in country column
df['country'] = df['country'].fillna('Unknown')

In [20]:
# coverting data types of columns and replacing missing with 0
df['agent'] = df['agent'].fillna(0).astype(int)
df['company'] = df['company'].fillna(0).astype(int)

In [38]:
# convert reservation Status date column into date format
df['reservation_status_date'] = pd.to_datetime(df['reservation_status_date'])

In [32]:
# remove duplicates
df = df.drop_duplicates()

In [26]:
# Remove Invalid Records
# Remove bookings with zero guests
df = df[(df['adults'] + df['children'] + df['babies']) > 0]

In [27]:
# Step 7: Handle Outliers
# Remove unrealistic ADR values
df = df[df['adr'] < 5000]

In [33]:
#Step 8: Feature Engineering
# Total Guests
df['total_guests'] = df['adults'] + df['children'] + df['babies']

In [34]:
# Total Stay
df['total_stay'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

In [35]:
# Convert monthname to month_number 
df['arrival_date_month'] = pd.to_datetime(df['arrival_date_month'], format='%B').dt.month

In [36]:
# Convert Categorical for ML
df = pd.get_dummies(df, columns=['hotel', 'deposit_type', 'customer_type'], drop_first=True)

In [39]:
# Final Check
df.info()
df.head()
df.isnull().sum()

<class 'pandas.DataFrame'>
Index: 87229 entries, 0 to 119389
Data columns (total 37 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   is_canceled                     87229 non-null  int64
 1   lead_time                       87229 non-null  int64
 2   arrival_date_year               87229 non-null  int64
 3   arrival_date_month              87229 non-null  int32
 4   arrival_date_week_number        87229 non-null  int64
 5   arrival_date_day_of_month       87229 non-null  int64
 6   stays_in_weekend_nights         87229 non-null  int64
 7   stays_in_week_nights            87229 non-null  int64
 8   adults                          87229 non-null  int64
 9   children                        87229 non-null  int64
 10  babies                          87229 non-null  int64
 11  meal                            87229 non-null  str
 12  country                         87229 non-null  str
 13  market_segment                  87229 non-null  str
 14  distribution_channel            87229 non-null  str
 15  is_repeated_guest               87229 non-null  int64
 16  previous_cancellations          87229 non-null  int64
 17  previous_bookings_not_canceled  87229 non-null  int64
 18  reserved_room_type              87229 non-null  str
 19  assigned_room_type              87229 non-null  str
 20  booking_changes                 87229 non-null  int64
 21  agent                           87229 non-null  int64
 22  company                         87229 non-null  int64
 23  days_in_waiting_list            87229 non-null  int64
 24  adr                             87229 non-null  float64
 25  required_car_parking_spaces     87229 non-null  int64
 26  total_of_special_requests       87229 non-null  int64
 27  reservation_status              87229 non-null  str
 28  reservation_status_date         87229 non-null  datetime64[us]
 29  total_guests                    87229 non-null  int64
 30  total_stay                      87229 non-null  int64
 31  hotel_Resort Hotel              87229 non-null  bool
 32  deposit_type_Non Refund         87229 non-null  bool
 33  deposit_type_Refundable         87229 non-null  bool
 34  customer_type_Group             87229 non-null  bool
 35  customer_type_Transient         87229 non-null  bool
 36  customer_type_Transient-Party   87229 non-null  bool
dtypes: bool(6), datetime64[us](1), float64(1), int32(1), int64(21), str(7)
memory usage: 21.5 MB

is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
agent                             0
company                           0
days_in_waiting_list              0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
total_guests                      0
total_stay                        0
hotel_Resort Hotel                0
deposit_type_Non Refund           0
deposit_type_Refundable           0
customer_type_Group               0
customer_type_Transient           0
customer_type_Transient-Party     0
dtype: int64

In [40]:
# Save Cleaned dataset
df.to_csv("cleaned_hotel_bookings.csv", index=False)